[theme]
base = "light"
primaryColor = "#398980"
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
linkColor = "#007BFF"
codeBackgroundColor = "#F0F2F6"
font = "sans-serif"
codeFont = "monospace"
headingFont = "sans-serif"
baseRadius = "small"
borderColor = "#E6E6E6"
showWidgetBorder = true
baseFontSize = 16
showSidebarBorder = true

[theme.sidebar]
# Custom theme just for the sidebar
backgroundColor = "#FFFFFF"
textColor = "#003D6A"        # The custom blue from your sidebar
font = "sans-serif"

[browser]

[server]
port = 8501